# Generated by Django 5.0 on 2023-12-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('id_groot', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('categoria_status', models.CharField(max_length=100)),
            ],
        ),
    ]
